### ISSUE TITLE
Migrating to null safety

### ISSUE THREAD

**Issue by hungps** [hungps/flutter_pokedex#36]
- [ ] Update the framework to the latest version
- [ ] Migrating the source code to [null safety](https://dart.dev/null-safety/migration-guide)

**Comment by abhi-shek2000** [comment]
Are you working on this? If not may I work on this?

**Comment by scitbiz** [comment]
@abhi-shek2000 I'm busy these days so nothing much has been done. It would be awesome if you can join in. Thanks!

**Comment by abhi-shek2000** [comment]
Okay Thanks :)

**Comment by abhi-shek2000** [comment]
@scitbiz I've completed the task please review the Pull Request :)
