### ISSUE TITLE
Support for web and desktop app

### ISSUE THREAD

**Issue by hungps** [hungps/flutter_pokedex#37]

**Comment by rishab2890** [comment]
May i work on this?

**Comment by scitbiz** [comment]
@rishab2890 Oh year sure, thank you!

**Comment by hungps** [comment]
@MayankChopra12 Sure, why not

**Comment by moulibheemaneti** [comment]
Hey, hi @hungps .

Currently I'm working flutter itself. Your app seems interesting. And I love the fact that it has smooth animations in it. I would like to work on this issue. Can I start working on this?

**Comment by hugovidafe** [comment]
Any update?

**Comment by moulibheemaneti** [comment]
> Any update?

I'm sorry bro. I was stuck up with some office works. So couldn't spend time on it yet. I guess I could spend sometime now. I'll update you in a day or two.

**Comment by AlexHRodrii** [comment]
Can I work on it?

**Comment by felipecastrosales** [comment]
Anyone can open your PR or fork. 
This repository is open-source, @AlexHRodrii. :)

**Comment by felipecastrosales** [comment]
Also, there is quite an interesting PR about it. 
- #https://github.com/hungps/flutter_pokedex/pull/73

**Comment by hungps** [comment]
Fixed by #73

**Comment by moulibheemaneti** [comment]
> > Any update?
> 
> I'm sorry bro. I was stuck up with some office works. So couldn't spend time on it yet. I guess I could spend sometime now. I'll update you in a day or two.

@hungps 

First of all I want to thank you for entrusting me with this task initially. I understand that taking up the task and not doing isn't appropriate. I know any reason mentioning wouldn't suffice. But I was in no condition to do other works for past 4 months. Hope you understand.
Thank you and see you soon with some or the other issues or PRs.
