### ISSUE TITLE
Option for Dark Theme

### ISSUE THREAD

**Issue by abhi-shek2000** [hungps/flutter_pokedex#42]
Add option for the User to choose/change the theme (Dark, Light (current theme)).

**Comment by TusharKalyankar** [comment]
Hi Abhishek, I would like to try to work on this.

**Comment by TusharKalyankar** [comment]
@abhi-shek2000  @scitbiz

**Comment by scitbiz** [comment]
@TusharKalyankar Great, thanks!

**Comment by fuadreza** [comment]
I would like to work on this.. Thankyou..
