### ISSUE TITLE
Feature: Dynamic titles for screens

### ISSUE THREAD

**Issue by hugovidafe** [hungps/flutter_pokedex#60]
We're seeing 'Pokedex' on all the screens except for 'Type Effects', because we are saying explicitly the name of the screen:
![image](https://user-images.githubusercontent.com/69076992/161621083-6b1cffa3-4951-4171-a937-cd621f4b6005.png)

We should use something like this on all screens:
![image](https://user-images.githubusercontent.com/69076992/161620880-d736a3c4-9078-42d1-b967-3fdf0528bd60.png)

But first it would be necessary to integrate that the title is changed automatically when changing the route.

**Comment by hungps** [comment]
@hugovidafe  That could be, but some of the screens use customized AppBar with the dynamic title (for example `pokemon_info`), and by specifying the global AppBar we are forced to use it on every screen. Unless there is a way to override our customized global AppBar. Any idea?
