### ISSUE TITLE
Images not fetching for web support.

### ISSUE THREAD

**Issue by moulibheemaneti** [hungps/flutter_pokedex#70]
Hey @hungps,
I'm starting the web support for the app too. While doing so, we are not able to fetch images.

<img width="1421" alt="Screenshot 2022-11-01 at 12 22 07 PM" src="https://user-images.githubusercontent.com/57999522/199176039-36c5c323-82e8-4329-9c3a-9877635f06c2.png">

And the error in terminal is:
<img width="1171" alt="Screenshot 2022-11-01 at 12 22 47 PM" src="https://user-images.githubusercontent.com/57999522/199176151-d4f2243d-cf29-4578-91ca-26fc0a288da6.png">

But the image url in terminal is getting redirected.

**Comment by hungps** [comment]
Hi @moulibheemaneti,
Thank you for contributing. The host (pokemon.com) might prevent another website from using their images. I'm planning on cloning the image and hosting it in Github to solve this.

**Comment by moulibheemaneti** [comment]
I guess that would solve the problem. But I guess there will some limit for storing right?

**Comment by hungps** [comment]
@moulibheemaneti Actually PokéAPI has done this (even much more images than we need to use in our app). We might simply clone their repo and remove unnecessary things. You can see the sprites that we need to clone [here](https://github.com/PokeAPI/sprites/tree/master/sprites/pokemon/other/official-artwork)

You can try something like this to get the image URL: `https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/{pokemon-number}.png`

For example: https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/1.png

**Comment by moulibheemaneti** [comment]
@hungps woah. That's great. Let's do what you suggested.

**Comment by moulibheemaneti** [comment]
@hungps Can I contact you through LinkedIn?

**Comment by hungps** [comment]
@moulibheemaneti I will prepare another repository for storing the images (maybe this weekend) and give you the link when I'm finished. If you are currently working on it, you can use the PokeAPI URL temporarily for now.

**Comment by hungps** [comment]
@moulibheemaneti 
> Can I contact you through LinkedIn?

Sure, just send me a request

**Comment by moulibheemaneti** [comment]
> @moulibheemaneti
> 
> > Can I contact you through LinkedIn?
> 
> Sure, just send me a request

Yeah I just sent.

**Comment by hungps** [comment]
@moulibheemaneti I've forked the PokéAPI's sprites repository. You can now load the pokemon image by using this format:
`https://raw.githubusercontent.com/hungps/flutter_pokedex_db/master/sprites/pokemon/other/official-artwork/{pokemon-number}.png`
