### ISSUE TITLE
Error compiling this for linux

### ISSUE THREAD

**Issue by Yorisoft** [hungps/flutter_pokedex#78]
Let me start off by saying thanks for the great app! Can never go wrong with having a pokedex handy. 

Im trying to compile this for a retroHandheld, miyoomini. I think itd be great to have it handy and I'd also like to contribute to the retro community. 

When trying to compile the app I keep encountering an error. 

```
Exception: Unsupported platform name "Debug"
#0      getTargetPlatformForName (package:flutter_tools/src/build_info.dart:772:3)
#1      AssembleCommand.requiredArtifacts (package:flutter_tools/src/commands/assemble.dart:159:43)
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1519:43)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1336:27)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#5      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#6      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:296:9)
<asynchronous suspension>
#7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#8      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:244:5)
<asynchronous suspension>
#9      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:91:9)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#11     main (package:flutter_tools/executable.dart:91:3)
<asynchronous suspension>

make[2]: *** [flutter/CMakeFiles/flutter_assemble.dir/build.make:84: flutter/ephemeral/libflutter_linux_gtk.so] Error 1
make[2]: Leaving directory '/root/workspace/flutter_pokedex/linux'
make[1]: *** [CMakeFiles/Makefile2:131: flutter/CMakeFiles/flutter_assemble.dir/all] Error 2
make[1]: Leaving directory '/root/workspace/flutter_pokedex/linux'
make: *** [Makefile:133: all] Error 2
```

Ive tried hardcoding a few different values but can never get it to work. Dont really know what I'm doing haha.
Any help would be greatly appreciated!!

**Comment by hungps** [comment]
Hi @Yorisoft,
I don't have the Miyoomini device so I'm not sure what OS it runs. Could you please share a little bit about the device and what command you have tried to build the app so maybe I could help you with that?

**Comment by Yorisoft** [comment]
Te miyoo mini is a small retro handheld. The most popular OS ppl like to run on it is Onion OS. 

It's a very bare bones OS for running GUI and retro emulators. 

I'm actually not that experienced of dev. But I found a miyoo mini tool chain and have found a lot of help on the onion OS discord. 

After spending some more time trying to get this app to work I learned that the OS doesn't support the dependencies for it. That's because it doesn't support gtk or X server.

 I've been trying to get something with SDL working. But I you can convert your app to run on the miyoo mini toolchain it can run on the miyoo devices! A Pokedex would be great!

**Comment by hungps** [comment]
@Yorisoft I agree that having a Pokedex inside a gaming console is pretty neat. Unfortunately, I don't have the device to test the app. I don't even have a Linux machine at the moment so I'm sorry to say that I cannot help you with this. If you ever figure it out in the future, don't hesitate to make a PR!
