### ISSUE TITLE
#numbers on Pokédex window

### ISSUE THREAD

**Issue by namangarg1902** [hungps/flutter_pokedex#83]
ISSUE:
The #number like #001 is looking off as it is getting blended into the background .
We can give it a white or its shade to enhance the UI of the screen .

**Comment by hungps** [comment]
@namangarg1902
Do you mean the Pokemon number (eg: `#001`) inside each card of the Pokedex page? 
IMO, it looks quite decent 🤔. It makes you focus more on the main information (name, types, sprite) than the number itself, which I think is only useful for searching. 

It's even harder to see in the [original design](https://dribbble.com/shots/6545819-Pokedex-App)

**Comment by namangarg1902** [comment]
No , I was talking about the number on Pokédex window itself not inside each and every card

**Comment by hungps** [comment]
@namangarg1902 
Could you please attach a screenshot of the one you're talking about?
